name: 'website'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/etc/nginx/logs
      - ./data:/etc/nginx/data
      - ./public:/etc/nginx/public
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - all

networks:
  all:
    driver: bridge
